In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv('E:/wine-quality-white-and-red.csv')

df = pd.DataFrame(dataset) 
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [5]:
dfd = df.drop( ['type'] , axis=1 )
X = dfd.drop( ['quality'] , axis = 1 )
y = dfd['quality'] 

In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

In [152]:
#NB  = GaussianNB()
#KNN = KNeighborsClassifier(n_neighbors=9)
RF  = RandomForestClassifier(criterion='gini',n_estimators=10 ,max_depth=22,random_state=0) 

In [153]:
#MLP = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1) , alpha=1e-5, random_state=1) 
#SVM = SVC(C=1, kernel = 'rbf', random_state = 0, gamma='scale')

In [154]:
from sklearn.model_selection import train_test_split

In [155]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=0)

In [156]:
Xtrain.shape

(4547, 11)

In [157]:
ytest.shape

(1950,)

In [158]:
ytest

5316    6
5210    6
3518    5
1622    6
2443    5
       ..
6277    6
3035    7
3410    7
6099    7
5781    5
Name: quality, Length: 1950, dtype: int64

In [159]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(Xtrain)  
Xtrain = scaler.transform(Xtrain)  
Xtest  = scaler.transform(Xtest) 

In [160]:
#NB.fit (Xtrain , ytrain)
#KNN.fit(Xtrain , ytrain)
RF.fit (Xtrain , ytrain)

RandomForestClassifier(max_depth=22, n_estimators=10, random_state=0)

In [161]:
#MLP.fit(Xtrain , ytrain) 
#SVM.fit(Xtrain , ytrain)

In [162]:
#ypNB   = NB.predict(Xtest)
#ypKNN  = KNN.predict(Xtest)
ypRF   = RF.predict(Xtest)

In [163]:
#ypMLP  = MLP.predict(Xtest)
#ypSVM  = SVM.predict(Xtest)

In [164]:
#NB.score (Xtrain , ytrain)  
#KNN.score(Xtrain , ytrain)   
RF.score (Xtrain , ytrain)  

0.9848251594457884

In [165]:
#NB.score (Xtest , ytest)   
#KNN.score(Xtest , ytest)  
RF.score (Xtest , ytest)   

0.6558974358974359

In [166]:
#SVM.score(Xtrain , ytrain)   
#MLP.score(Xtrain , ytrain) 

In [167]:
#MLP.score(Xtest , ytest)  
#SVM.score(Xtest , ytest) 

In [168]:
import numpy as np

In [169]:
from  sklearn.model_selection   import  cross_val_score

In [179]:
#np.mean(cross_val_score(NB  , X , y , cv=10))   
#np.mean(cross_val_score(KNN , X , y , cv=10))   
np.mean(cross_val_score(RF  , X , y , cv=30))   

E:\anaconda\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=30.
  UserWarning,


0.5219505603914206

In [182]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
Xf = SelectKBest(chi2, k=1).fit_transform(X, y)
Xf

array([[170.],
       [132.],
       [ 97.],
       ...,
       [ 40.],
       [ 44.],
       [ 42.]])

In [183]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True) 
xfs = model.transform(X)
xfs

E:\anaconda\lib\site-packages\sklearn\svm\_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
E:\anaconda\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


array([[  7.   ,   0.27 ,  20.7  , ..., 170.   ,   3.   ,   8.8  ],
       [  6.3  ,   0.3  ,   1.6  , ..., 132.   ,   3.3  ,   9.5  ],
       [  8.1  ,   0.28 ,   6.9  , ...,  97.   ,   3.26 ,  10.1  ],
       ...,
       [  6.3  ,   0.51 ,   2.3  , ...,  40.   ,   3.42 ,  11.   ],
       [  5.9  ,   0.645,   2.   , ...,  44.   ,   3.57 ,  10.2  ],
       [  6.   ,   0.31 ,   3.6  , ...,  42.   ,   3.39 ,  11.   ]])

In [184]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
clf = ExtraTreesClassifier(n_estimators=50)
clf = clf.fit(X, y)
clf.feature_importances_  

array([0.07950251, 0.10276549, 0.08235146, 0.08380603, 0.08220444,
       0.08601032, 0.08766845, 0.09360726, 0.08185122, 0.08634252,
       0.13389031])